// Active pending applications queue
// Key: appId (string)
// Value: { id, username, discordId, edition, submittedAt }
export const pendingApplications = new Map();

// Tokens generated by the Discord bot when users click Apply
// Key: token (string)
// Value: { discordId, createdAt }
export const preAuthTokens = new Map();

// Quick stats tracking (persisted in-memory)
export const stats = {
  approvedCount: 0,
  rejectedCount: 0
};
